version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d


#  redis:
#    image: redis:7-alpine
#    container_name: redis
#    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#    ports:
#      - "6363:6379"
#    volumes:
#      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#      - ./redis/users.acl:/etc/redis/users.acl
#
#  localstack:
#    image: localstack/localstack:3.0
#    container_name: localstack
#    ports:
#      - "4566:4566"
#    environment:
#      - SERVICES=sns,sqs
#      - AWS_ACCESS_KEY_ID=local
#      - AWS_SECRET_ACCESS_KEY=local
#      - AWS_DEFAULT_REGION=ap-northeast-2
#    volumes:
#      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
#      - /var/run/docker.sock:/var/run/docker.sock
#
#  mongo:
#    image: mongo:7
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_PASSWORD=local
#      - MONGO_INITDB_ROOT_USERNAME=local
#      - MONGO_INITDB_ROOT_DATABASE=local
#
#  elasticsearch:
#    build:
#      context: ./elasticsearch
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - ELASTIC_USERNAME=local
#      - ELASTIC_PASSWORD=local
#      - ES_JAVA_OPTS=-Xms1g -Xmx1g
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#
#  kafka1:
#    image: confluentinc/cp-kafka:7.7.0
#    hostname: kafka1
#    container_name: kafka1
#    ports:
#      - "9092:9092"
#      - "19092:19092"
#    environment:
#      CLUSTER_ID: kafka-cluster
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_JMX_HOSTNAME: localhost
#      KAFKA_JMX_PORT: 19092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
#      KAFKA_LISTENERS: INTERNAL://kafka1:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
#
#  kafka2:
#    image: confluentinc/cp-kafka:7.7.0
#    hostname: kafka2
#    container_name: kafka2
#    ports:
#      - "9093:9093"
#    environment:
#      CLUSTER_ID: kafka-cluster
#      KAFKA_NODE_ID: 2
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_JMX_HOSTNAME: localhost
#      KAFKA_JMX_PORT: 19092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://localhost:9093
#      KAFKA_LISTENERS: INTERNAL://kafka2:29092,CONTROLLER://kafka2:29093,EXTERNAL://0.0.0.0:9093
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
#
#  kafka3:
#    image: confluentinc/cp-kafka:7.7.0
#    hostname: kafka3
#    container_name: kafka3
#    ports:
#      - "9094:9094"
#    environment:
#      CLUSTER_ID: kafka-cluster
#      KAFKA_NODE_ID: 3
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_JMX_HOSTNAME: localhost
#      KAFKA_JMX_PORT: 19092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://localhost:9094
#      KAFKA_LISTENERS: INTERNAL://kafka3:29092,CONTROLLER://kafka3:29093,EXTERNAL://0.0.0.0:9094
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
#
#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - "9999:8080"
#    depends_on:
#      - kafka1
#      - kafka2
#      - kafka3
#    environment:
#      KAFKA_CLUSTERS_0_NAME: kafka-cluster
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092,kafka2:29092,kafka3:29092
#      KAFKA_CLUSTERS_0_METRICS_PORT: 19092
#      DYNAMIC_CONFIG_ENABLED: 'true'