name: server ci

on:
  push:
    tags:
      - v*.*.*

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_NAMESPACE: {{ use your namespace here }}
  MODULE_NAME: {{ use your build module name here }}

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Tag
        id: tag
        run: echo "v=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_OUTPUT

      - name: Docker Build & Push
        env:
          IMAGE_TAG: "${{ env.GHCR_REGISTRY }}/${{ env.GHCR_NAMESPACE }}/${{ env.MODULE_NAME }}:${{steps.tag.outputs.v}}"
        run: |
          make docker module=${{ env.MODULE_NAME }} tag=${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_TAG }}