name: server ci

on:
  push:
    tags:
      - v*.*.*

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_NAMESPACE: {{ use your namespace here }}
  APP_NAME: {{ use your app name here }}

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract tag version
        id: tag
        run: echo "v=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_OUTPUT

      - name: image build & push ghcr
        env:
          IMAGE_TAG: "${{ env.GHCR_REGISTRY }}/${{ env.GHCR_NAMESPACE }}/${{ env.APP_NAME }}:${{steps.tag.outputs.v}}"
        run: |
          make docker tag=${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_TAG }}