name: server ci

on:
  push:
    tags:
      - server-v*.*.*

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_NAMESPACE: nopechouniverse
  APP_NAME: server

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract version
        id: app_version
        run: echo "version=$(echo ${GITHUB_REF#refs/tags/${{ env.APP_NAME }}-v})" >> $GITHUB_OUTPUT

      - name: build and push to ghcr
        env:
          APP_VERSION: ${{ steps.app_version.outputs.version }}
        run: |
          make docker tag=${{ env.GHCR_REGISTRY }}/${{ env.GHCR_NAMESPACE }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}
          docker push ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_NAMESPACE }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}